#!/usr/bin/env groovy
#master change only for comments.
pipeline {
	agent any
	
	stages {
		stage('Build') {
			steps {
				echo "Building.. Path Before: ${env.PATH}"
				//env.PATH="${env.PATH}:/usr/bin"
				echo "Building.. Path After: ${env.PATH}"
			}
		}
		stage('Test')  {
			steps {
				echo "Testing.. Build name: ${currentBuild.displayName}"
			//	echo $currentBuild.displayName
				
			}
		}
		stage('Deploy') {
			steps {
				echo 'Deploy..'
			}
		}
	}
	
}
